name: Ejecutar Scraper de Cervezas

on:
  workflow_dispatch: # Botón para ejecutar manualmente cuando quieras

jobs:
  scraping:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio y archivos
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerías
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests openpyxl urllib3

      - name: Ejecutar scraper
        run: python main.py
